# -*- coding: utf-8 -*-
"""TUBES SA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WrzSBPQqIZIRjfsPK5qalhyIoiUKkgz9

Tugas Besar Strategi Algoritma 

Anggota :

1.   Hanifan Nurul Haq (1301218609)
2.   Muhammad Zaki Alkhairi (1301218590)
3. Yolanda Stefani Putri br Purba (1301218602)



Kasus : Maximum Profit by buying and selling a share at most k times
Strategi : Greedy and Brute Force

Brute Force
"""

def maxProfit(prices):
  max_profit = 0
  for i in range(1,len(prices)):
      if prices[i] - prices[i-1] >0:
          max_profit+=(prices[i] - prices[i-1])
  return max_profit

prices = [80, 120, 65, 200, 430, 520, 600 ]
print('max profit: ', maxProfit(prices))

"""Greedy"""

def maxProfit(prices):
  profit = 0
  for i in range(1, len(prices)):
      profit = max(profit, profit + prices[i] - prices[i-1])
  return profit

prices = [80, 120, 65, 200, 430, 520, 600 ]
print('max profit: ', maxProfit(prices))